# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: LocalStack
    init: pip install localstack
    command: localstack start
      
  - name: AWS CLI and SAM
    init: >
      pip install aws-sam-cli &&
      pip install aws-sam-cli-local &&
      pip install awscli &&
      pip install awscli-local

  - init: pip install -r requirements.txt

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
