AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  100-bagger-stock-screener

  SAM Template for 100-bagger-stock-screener

Resources:
  # StockTradingStateMachine:
  #   Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
  #   Properties:
  #     DefinitionUri: statemachine/stock_trader.asl.json
  #     DefinitionSubstitutions:
  #       StockCheckerFunctionArn: !GetAtt StockCheckerFunction.Arn
  #       StockSellerFunctionArn: !GetAtt StockSellerFunction.Arn
  #       StockBuyerFunctionArn: !GetAtt StockBuyerFunction.Arn
  #       DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
  #       DDBTable: !Ref TransactionTable
  #     Events:
  #       HourlyTradingSchedule:
  #         Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
  #         Properties:
  #           Description: Schedule to run the stock trading state machine every hour
  #           Enabled: False # This schedule is disabled by default to avoid incurring charges.
  #           Schedule: "rate(1 hour)"
  #     Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
  #       - LambdaInvokePolicy:
  #           FunctionName: !Ref StockCheckerFunction
  #       - LambdaInvokePolicy:
  #           FunctionName: !Ref StockSellerFunction
  #       - LambdaInvokePolicy:
  #           FunctionName: !Ref StockBuyerFunction
  #       - DynamoDBWritePolicy:
  #           TableName: !Ref TransactionTable

  StockListFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/stock_list/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 20
      Architectures:
        - x86_64

  StockDataFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/stock_data/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 20
      Architectures:
        - x86_64

  StockTable:
    Type: AWS::Serverless::SimpleTable 
    Properties:
      PrimaryKey:
        Name: ISIN
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


# Outputs:
#   StockTradingStateMachineArn:
#     Description: "Stock Trading State machine ARN"
#     Value: !Ref StockTradingStateMachine
#   StockTradingStateMachineRoleArn:
#     Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
#     Value: !GetAtt StockTradingStateMachineRole.Arn
