AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  100-bagger-stock-screener

  SAM Template for 100-bagger-stock-screener

Resources:
  StockProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/stock_processor.asl.json
      DefinitionSubstitutions:
        StockListFunctionArn: !GetAtt StockListFunction.Arn
        StockDataFunctionArn: !GetAtt StockDataFunction.Arn
        StockEmailFunctionArn: !GetAtt StockEmailFunction.Arn
      Events:
        WeeklyStockProcessingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every week
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(7 days)"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref StockListFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockDataFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockEmailFunction


  StockListFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/stock_list/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 20
      Architectures:
        - x86_64

  StockDataFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/stock_data/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 20
      Architectures:
        - x86_64

  StockEmailFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/stock_email/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 10
      Architectures:
        - x86_64
      Policies:
        - AmazonSESFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"


Outputs:
  StockProcessingStateMachineArn:
    Description: "Stock Processing State machine ARN"
    Value: !Ref StockProcessingStateMachine
  StockProcessingStateMachineRoleArn:
    Description: "IAM Role created for Stock Processing State machine based on the specified SAM Policy Templates"
    Value: !GetAtt StockProcessingStateMachineRole.Arn
